### ISSUE TITLE
[Question] Save final recommendations (into csv)

### ISSUE THREAD

**Issue by SlokomManel** [pretrain/pretrain#1]
Dear pretrain authors,

Recently, I came across your repository. I am still exploring it and reading your paper. I was able to run and reproduce some experiments following your instructions. 
I would like to ask you on whether it is possible to generate topN recommendation per user and if it is possible to save them to csv file. 

Thank you,
Bests.
~_Manel_.

**Comment by SlokomManel** [comment]
Hi,

Could you also let us know how you randomly dropped different proportions ({20%, 40%, 60%, 80%}) of entity features? I did not come across it in the code. Is it done manually? 

Would it be possible to choose specific user / item features? For instance, what if we only have user features ?

Looking forward to hearing back from you.

Thank you,
Bests.

**Comment by pretrain** [comment]
Hi Manel,

I believe I have answered most of your questions by email. 
But for other readers, if you want to save any result, please you can find the variable test_pred  in [evel_engine.py](https://github.com/pretrain/pretrain/blob/a948e3ef5d02c3094602f4feaf82f76dacf8ac85/src/eval_engine.py#L307) for the predictions, where you can save your predictions here. Mostly we use 10 different test/validation sets (checkout paper for the evaluation protocal detail) so in this function we enumerate all the 10 sets.

Regarding the randomly dropped different proportions, that was probably done by another copied codes. But you can choose different feature of users or items by modify your codes of here [here](https://github.com/pretrain/pretrain/blob/a948e3ef5d02c3094602f4feaf82f76dacf8ac85/src/datasets/movielens.py#L81).

Bests,
Zaiqiao

**Comment by SlokomManel** [comment]
Thank you Zaiqiao for your reply! 
Kind regards.
~_Manel_.
